DROP TABLE IF EXISTS Language;
CREATE TABLE Language (
  iso1 TEXT NOT NULL,
  script TEXT NOT NULL,
  name TEXT NOT NULL,
  PRIMARY KEY (iso1, script));
INSERT INTO Language VALUES ('af', '', 'Afrikaans');
INSERT INTO Language VALUES ('agq', '', 'Aghem');
INSERT INTO Language VALUES ('ak', '', 'Akan');
INSERT INTO Language VALUES ('am', '', 'Amharic');
INSERT INTO Language VALUES ('ar', '', 'Arabic');
INSERT INTO Language VALUES ('as', '', 'Assamese');
INSERT INTO Language VALUES ('asa', '', 'Asu');
INSERT INTO Language VALUES ('ast', '', 'Asturian');
INSERT INTO Language VALUES ('az', '', 'Azerbaijani');
INSERT INTO Language VALUES ('az', 'Cyrl', 'Azerbaijani (Cyrillic)');
INSERT INTO Language VALUES ('az', 'Latn', 'Azerbaijani (Latin)');
INSERT INTO Language VALUES ('bas', '', 'Basaa');
INSERT INTO Language VALUES ('be', '', 'Belarusian');
INSERT INTO Language VALUES ('bem', '', 'Bemba');
INSERT INTO Language VALUES ('bez', '', 'Bena');
INSERT INTO Language VALUES ('bg', '', 'Bulgarian');
INSERT INTO Language VALUES ('bm', '', 'Bambara');
INSERT INTO Language VALUES ('bn', '', 'Bangla');
INSERT INTO Language VALUES ('bo', '', 'Tibetan');
INSERT INTO Language VALUES ('br', '', 'Breton');
INSERT INTO Language VALUES ('brx', '', 'Bodo');
INSERT INTO Language VALUES ('bs', '', 'Bosnian');
INSERT INTO Language VALUES ('bs', 'Cyrl', 'Bosnian (Cyrillic)');
INSERT INTO Language VALUES ('bs', 'Latn', 'Bosnian (Latin)');
INSERT INTO Language VALUES ('ca', '', 'Catalan');
INSERT INTO Language VALUES ('ccp', '', 'Chakma');
INSERT INTO Language VALUES ('ce', '', 'Chechen');
INSERT INTO Language VALUES ('cgg', '', 'Chiga');
INSERT INTO Language VALUES ('chr', '', 'Cherokee');
INSERT INTO Language VALUES ('ckb', '', 'Central Kurdish');
INSERT INTO Language VALUES ('cs', '', 'Czech');
INSERT INTO Language VALUES ('cy', '', 'Welsh');
INSERT INTO Language VALUES ('da', '', 'Danish');
INSERT INTO Language VALUES ('dav', '', 'Taita');
INSERT INTO Language VALUES ('de', '', 'German');
INSERT INTO Language VALUES ('dje', '', 'Zarma');
INSERT INTO Language VALUES ('dsb', '', 'Lower Sorbian');
INSERT INTO Language VALUES ('dua', '', 'Duala');
INSERT INTO Language VALUES ('dyo', '', 'Jola-Fonyi');
INSERT INTO Language VALUES ('dz', '', 'Dzongkha');
INSERT INTO Language VALUES ('ebu', '', 'Embu');
INSERT INTO Language VALUES ('ee', '', 'Ewe');
INSERT INTO Language VALUES ('el', '', 'Greek');
INSERT INTO Language VALUES ('en', '', 'English');
INSERT INTO Language VALUES ('eo', '', 'Esperanto');
INSERT INTO Language VALUES ('es', '', 'Spanish');
INSERT INTO Language VALUES ('et', '', 'Estonian');
INSERT INTO Language VALUES ('eu', '', 'Basque');
INSERT INTO Language VALUES ('ewo', '', 'Ewondo');
INSERT INTO Language VALUES ('fa', '', 'Persian');
INSERT INTO Language VALUES ('ff', '', 'Fulah');
INSERT INTO Language VALUES ('fi', '', 'Finnish');
INSERT INTO Language VALUES ('fil', '', 'Filipino');
INSERT INTO Language VALUES ('fo', '', 'Faroese');
INSERT INTO Language VALUES ('fr', '', 'French');
INSERT INTO Language VALUES ('fur', '', 'Friulian');
INSERT INTO Language VALUES ('fy', '', 'Western Frisian');
INSERT INTO Language VALUES ('ga', '', 'Irish');
INSERT INTO Language VALUES ('gd', '', 'Scottish Gaelic');
INSERT INTO Language VALUES ('gl', '', 'Galician');
INSERT INTO Language VALUES ('gsw', '', 'Swiss German');
INSERT INTO Language VALUES ('gu', '', 'Gujarati');
INSERT INTO Language VALUES ('guz', '', 'Gusii');
INSERT INTO Language VALUES ('gv', '', 'Manx');
INSERT INTO Language VALUES ('ha', '', 'Hausa');
INSERT INTO Language VALUES ('haw', '', 'Hawaiian');
INSERT INTO Language VALUES ('he', '', 'Hebrew');
INSERT INTO Language VALUES ('hi', '', 'Hindi');
INSERT INTO Language VALUES ('hr', '', 'Croatian');
INSERT INTO Language VALUES ('hsb', '', 'Upper Sorbian');
INSERT INTO Language VALUES ('hu', '', 'Hungarian');
INSERT INTO Language VALUES ('hy', '', 'Armenian');
INSERT INTO Language VALUES ('id', '', 'Indonesian');
INSERT INTO Language VALUES ('ig', '', 'Igbo');
INSERT INTO Language VALUES ('ii', '', 'Sichuan Yi');
INSERT INTO Language VALUES ('is', '', 'Icelandic');
INSERT INTO Language VALUES ('it', '', 'Italian');
INSERT INTO Language VALUES ('iu', '', 'Inuktitut');
INSERT INTO Language VALUES ('ja', '', 'Japanese');
INSERT INTO Language VALUES ('jgo', '', 'Ngomba');
INSERT INTO Language VALUES ('jmc', '', 'Machame');
INSERT INTO Language VALUES ('ka', '', 'Georgian');
INSERT INTO Language VALUES ('kab', '', 'Kabyle');
INSERT INTO Language VALUES ('kam', '', 'Kamba');
INSERT INTO Language VALUES ('kde', '', 'Makonde');
INSERT INTO Language VALUES ('kea', '', 'Kabuverdianu');
INSERT INTO Language VALUES ('khq', '', 'Koyra Chiini');
INSERT INTO Language VALUES ('ki', '', 'Kikuyu');
INSERT INTO Language VALUES ('kk', '', 'Kazakh');
INSERT INTO Language VALUES ('kkj', '', 'Kako');
INSERT INTO Language VALUES ('kl', '', 'Kalaallisut');
INSERT INTO Language VALUES ('kln', '', 'Kalenjin');
INSERT INTO Language VALUES ('km', '', 'Khmer');
INSERT INTO Language VALUES ('kn', '', 'Kannada');
INSERT INTO Language VALUES ('ko', '', 'Korean');
INSERT INTO Language VALUES ('kok', '', 'Konkani');
INSERT INTO Language VALUES ('ks', '', 'Kashmiri');
INSERT INTO Language VALUES ('ksb', '', 'Shambala');
INSERT INTO Language VALUES ('ksf', '', 'Bafia');
INSERT INTO Language VALUES ('ksh', '', 'Colognian');
INSERT INTO Language VALUES ('kw', '', 'Cornish');
INSERT INTO Language VALUES ('ky', '', 'Kyrgyz');
INSERT INTO Language VALUES ('lag', '', 'Langi');
INSERT INTO Language VALUES ('lb', '', 'Luxembourgish');
INSERT INTO Language VALUES ('lg', '', 'Ganda');
INSERT INTO Language VALUES ('lkt', '', 'Lakota');
INSERT INTO Language VALUES ('ln', '', 'Lingala');
INSERT INTO Language VALUES ('lo', '', 'Lao');
INSERT INTO Language VALUES ('lrc', '', 'Northern Luri');
INSERT INTO Language VALUES ('lt', '', 'Lithuanian');
INSERT INTO Language VALUES ('lu', '', 'Luba-Katanga');
INSERT INTO Language VALUES ('luo', '', 'Luo');
INSERT INTO Language VALUES ('luy', '', 'Luyia');
INSERT INTO Language VALUES ('lv', '', 'Latvian');
INSERT INTO Language VALUES ('mas', '', 'Masai');
INSERT INTO Language VALUES ('mer', '', 'Meru');
INSERT INTO Language VALUES ('mfe', '', 'Morisyen');
INSERT INTO Language VALUES ('mg', '', 'Malagasy');
INSERT INTO Language VALUES ('mgh', '', 'Makhuwa-Meetto');
INSERT INTO Language VALUES ('mgo', '', 'Metaʼ');
INSERT INTO Language VALUES ('mk', '', 'Macedonian');
INSERT INTO Language VALUES ('ml', '', 'Malayalam');
INSERT INTO Language VALUES ('mn', '', 'Mongolian');
INSERT INTO Language VALUES ('mr', '', 'Marathi');
INSERT INTO Language VALUES ('ms', '', 'Malay');
INSERT INTO Language VALUES ('ms', 'Arab', 'Malay (Arabic)');
INSERT INTO Language VALUES ('mt', '', 'Maltese');
INSERT INTO Language VALUES ('mua', '', 'Mundang');
INSERT INTO Language VALUES ('my', '', 'Burmese');
INSERT INTO Language VALUES ('mzn', '', 'Mazanderani');
INSERT INTO Language VALUES ('naq', '', 'Nama');
INSERT INTO Language VALUES ('nb', '', 'Norwegian Bokmål');
INSERT INTO Language VALUES ('nd', '', 'North Ndebele');
INSERT INTO Language VALUES ('nds', '', 'Low German');
INSERT INTO Language VALUES ('ne', '', 'Nepali');
INSERT INTO Language VALUES ('nl', '', 'Dutch');
INSERT INTO Language VALUES ('nmg', '', 'Kwasio');
INSERT INTO Language VALUES ('nn', '', 'Norwegian Nynorsk');
INSERT INTO Language VALUES ('nnh', '', 'Ngiemboon');
INSERT INTO Language VALUES ('nus', '', 'Nuer');
INSERT INTO Language VALUES ('nyn', '', 'Nyankole');
INSERT INTO Language VALUES ('om', '', 'Oromo');
INSERT INTO Language VALUES ('or', '', 'Odia');
INSERT INTO Language VALUES ('os', '', 'Ossetic');
INSERT INTO Language VALUES ('pa', '', 'Punjabi');
INSERT INTO Language VALUES ('pa', 'Arab', 'Punjabi (Arabic)');
INSERT INTO Language VALUES ('pa', 'Guru', 'Punjabi (Gurmukhi)');
INSERT INTO Language VALUES ('pl', '', 'Polish');
INSERT INTO Language VALUES ('ps', '', 'Pashto');
INSERT INTO Language VALUES ('pt', '', 'Portuguese');
INSERT INTO Language VALUES ('qu', '', 'Quechua');
INSERT INTO Language VALUES ('rm', '', 'Romansh');
INSERT INTO Language VALUES ('rn', '', 'Rundi');
INSERT INTO Language VALUES ('ro', '', 'Romanian');
INSERT INTO Language VALUES ('rof', '', 'Rombo');
INSERT INTO Language VALUES ('ru', '', 'Russian');
INSERT INTO Language VALUES ('rw', '', 'Kinyarwanda');
INSERT INTO Language VALUES ('rwk', '', 'Rwa');
INSERT INTO Language VALUES ('sah', '', 'Sakha');
INSERT INTO Language VALUES ('saq', '', 'Samburu');
INSERT INTO Language VALUES ('sbp', '', 'Sangu');
INSERT INTO Language VALUES ('se', '', 'Northern Sami');
INSERT INTO Language VALUES ('seh', '', 'Sena');
INSERT INTO Language VALUES ('ses', '', 'Koyraboro Senni');
INSERT INTO Language VALUES ('sg', '', 'Sango');
INSERT INTO Language VALUES ('shi', '', 'Tachelhit');
INSERT INTO Language VALUES ('shi', 'Latn', 'Tachelhit (Latin)');
INSERT INTO Language VALUES ('shi', 'Tfng', 'Tachelhit (Tifinagh)');
INSERT INTO Language VALUES ('si', '', 'Sinhala');
INSERT INTO Language VALUES ('sk', '', 'Slovak');
INSERT INTO Language VALUES ('sl', '', 'Slovenian');
INSERT INTO Language VALUES ('smn', '', 'Inari Sami');
INSERT INTO Language VALUES ('sn', '', 'Shona');
INSERT INTO Language VALUES ('so', '', 'Somali');
INSERT INTO Language VALUES ('sq', '', 'Albanian');
INSERT INTO Language VALUES ('sr', '', 'Serbian');
INSERT INTO Language VALUES ('sr', 'Cyrl', 'Serbian (Cyrillic)');
INSERT INTO Language VALUES ('sr', 'Latn', 'Serbian (Latin)');
INSERT INTO Language VALUES ('sv', '', 'Swedish');
INSERT INTO Language VALUES ('sw', '', 'Swahili');
INSERT INTO Language VALUES ('ta', '', 'Tamil');
INSERT INTO Language VALUES ('te', '', 'Telugu');
INSERT INTO Language VALUES ('teo', '', 'Teso');
INSERT INTO Language VALUES ('tg', '', 'Tajik');
INSERT INTO Language VALUES ('th', '', 'Thai');
INSERT INTO Language VALUES ('ti', '', 'Tigrinya');
INSERT INTO Language VALUES ('tk', '', 'Turkmen');
INSERT INTO Language VALUES ('to', '', 'Tongan');
INSERT INTO Language VALUES ('tr', '', 'Turkish');
INSERT INTO Language VALUES ('tt', '', 'Tatar');
INSERT INTO Language VALUES ('twq', '', 'Tasawaq');
INSERT INTO Language VALUES ('tzm', '', 'Central Atlas Tamazight');
INSERT INTO Language VALUES ('ug', '', 'Uyghur');
INSERT INTO Language VALUES ('uk', '', 'Ukrainian');
INSERT INTO Language VALUES ('ur', '', 'Urdu');
INSERT INTO Language VALUES ('uz', '', 'Uzbek');
INSERT INTO Language VALUES ('uz', 'Arab', 'Uzbek (Arabic)');
INSERT INTO Language VALUES ('uz', 'Cyrl', 'Uzbek (Cyrillic)');
INSERT INTO Language VALUES ('uz', 'Latn', 'Uzbek (Latin)');
INSERT INTO Language VALUES ('vai', '', 'Vai');
INSERT INTO Language VALUES ('vai', 'Latn', 'Vai (Latin)');
INSERT INTO Language VALUES ('vai', 'Vaii', 'Vai (Vai)');
INSERT INTO Language VALUES ('vi', '', 'Vietnamese');
INSERT INTO Language VALUES ('vun', '', 'Vunjo');
INSERT INTO Language VALUES ('wae', '', 'Walser');
INSERT INTO Language VALUES ('wo', '', 'Wolof');
INSERT INTO Language VALUES ('xog', '', 'Soga');
INSERT INTO Language VALUES ('yav', '', 'Yangben');
INSERT INTO Language VALUES ('yi', '', 'Yiddish');
INSERT INTO Language VALUES ('yo', '', 'Yoruba');
INSERT INTO Language VALUES ('yue', '', 'Cantonese');
INSERT INTO Language VALUES ('yue', 'Hans', 'Cantonese (Simplified)');
INSERT INTO Language VALUES ('yue', 'Hant', 'Cantonese (Traditional)');
INSERT INTO Language VALUES ('zgh', '', 'Standard Moroccan Tamazight');
INSERT INTO Language VALUES ('zh', '', 'Chinese');
INSERT INTO Language VALUES ('zh', 'Hans', 'Chinese (Simplified)');
INSERT INTO Language VALUES ('zh', 'Hant', 'Chinese (Traditional)');
INSERT INTO Language VALUES ('zu', '', 'Zulu');
